name = "cf-email-worker"
compatibility_date = "2024-01-17"
main = "src/index.ts"
node_compat = true

# D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "email-db"
database_id = "YOUR_D1_DATABASE_ID"

[observability]
enabled = true
